import 'package:flutter/material.dart';

/// generated by Material Theme Builder
/// https://material-foundation.github.io/material-theme-builder/
class MaterialTheme {
  const MaterialTheme(this.textTheme);

  final TextTheme textTheme;

  static MaterialScheme lightScheme() {
    return const MaterialScheme(
      brightness: Brightness.light,
      primary: Color(0xFF3D8A5A),
      surfaceTint: Color(0xFF3D8A5A),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFC8F0D8),
      onPrimaryContainer: Color(0xFF1A1918),
      secondary: Color(0xFF6D6C6A),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFEDECEA),
      onSecondaryContainer: Color(0xFF1A1918),
      tertiary: Color(0xFFD89575),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFF0E6),
      onTertiaryContainer: Color(0xFF1A1918),
      error: Color(0xFFD08068),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFAE5E0),
      onErrorContainer: Color(0xFF1A1918),
      background: Color(0xFFF5F4F1),
      onBackground: Color(0xFF1A1918),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF1A1918),
      surfaceVariant: Color(0xFFEDECEA),
      onSurfaceVariant: Color(0xFF6D6C6A),
      outline: Color(0xFFD1D0CD),
      outlineVariant: Color(0xFFE5E4E1),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF1A1918),
      inverseOnSurface: Color(0xFFFFFFFF),
      inversePrimary: Color(0xFFC8F0D8),
      primaryFixed: Color(0xFFC8F0D8),
      onPrimaryFixed: Color(0xFF1A1918),
      primaryFixedDim: Color(0xFFACF2C8),
      onPrimaryFixedVariant: Color(0xFF2D6B47),
      secondaryFixed: Color(0xFFEDECEA),
      onSecondaryFixed: Color(0xFF1A1918),
      secondaryFixedDim: Color(0xFF9C9B99),
      onSecondaryFixedVariant: Color(0xFF6D6C6A),
      tertiaryFixed: Color(0xFFFFF0E6),
      onTertiaryFixed: Color(0xFF1A1918),
      tertiaryFixedDim: Color(0xFFD89575),
      onTertiaryFixedVariant: Color(0xFFA86D4E),
      surfaceDim: Color(0xFFEDECEA),
      surfaceBright: Color(0xFFFFFFFF),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFFAFAF8),
      surfaceContainer: Color(0xFFF5F4F1),
      surfaceContainerHigh: Color(0xFFEDECEA),
      surfaceContainerHighest: Color(0xFFE5E4E1),
    );
  }

  ThemeData light() {
    return theme(lightScheme().toColorScheme());
  }


  ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        textTheme: textTheme.apply(
          bodyColor: colorScheme.onSurface,
          displayColor: colorScheme.onSurface,
        ),
        scaffoldBackgroundColor: colorScheme.surface,
        canvasColor: colorScheme.surface,
        extensions: [
          CustomColors.light(),
        ],
      );

  List<ExtendedColor> get extendedColors => [];
}

class MaterialScheme {
  const MaterialScheme({
    required this.brightness,
    required this.primary,
    required this.surfaceTint,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.background,
    required this.onBackground,
    required this.surface,
    required this.onSurface,
    required this.surfaceVariant,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.shadow,
    required this.scrim,
    required this.inverseSurface,
    required this.inverseOnSurface,
    required this.inversePrimary,
    required this.primaryFixed,
    required this.onPrimaryFixed,
    required this.primaryFixedDim,
    required this.onPrimaryFixedVariant,
    required this.secondaryFixed,
    required this.onSecondaryFixed,
    required this.secondaryFixedDim,
    required this.onSecondaryFixedVariant,
    required this.tertiaryFixed,
    required this.onTertiaryFixed,
    required this.tertiaryFixedDim,
    required this.onTertiaryFixedVariant,
    required this.surfaceDim,
    required this.surfaceBright,
    required this.surfaceContainerLowest,
    required this.surfaceContainerLow,
    required this.surfaceContainer,
    required this.surfaceContainerHigh,
    required this.surfaceContainerHighest,
  });

  final Brightness brightness;
  final Color primary;
  final Color surfaceTint;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color tertiary;
  final Color onTertiary;
  final Color tertiaryContainer;
  final Color onTertiaryContainer;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color background;
  final Color onBackground;
  final Color surface;
  final Color onSurface;
  final Color surfaceVariant;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color shadow;
  final Color scrim;
  final Color inverseSurface;
  final Color inverseOnSurface;
  final Color inversePrimary;
  final Color primaryFixed;
  final Color onPrimaryFixed;
  final Color primaryFixedDim;
  final Color onPrimaryFixedVariant;
  final Color secondaryFixed;
  final Color onSecondaryFixed;
  final Color secondaryFixedDim;
  final Color onSecondaryFixedVariant;
  final Color tertiaryFixed;
  final Color onTertiaryFixed;
  final Color tertiaryFixedDim;
  final Color onTertiaryFixedVariant;
  final Color surfaceDim;
  final Color surfaceBright;
  final Color surfaceContainerLowest;
  final Color surfaceContainerLow;
  final Color surfaceContainer;
  final Color surfaceContainerHigh;
  final Color surfaceContainerHighest;
}

extension MaterialSchemeUtils on MaterialScheme {
  ColorScheme toColorScheme() {
    return ColorScheme(
      brightness: brightness,
      primary: primary,
      onPrimary: onPrimary,
      primaryContainer: primaryContainer,
      onPrimaryContainer: onPrimaryContainer,
      secondary: secondary,
      onSecondary: onSecondary,
      secondaryContainer: secondaryContainer,
      onSecondaryContainer: onSecondaryContainer,
      tertiary: tertiary,
      onTertiary: onTertiary,
      tertiaryContainer: tertiaryContainer,
      onTertiaryContainer: onTertiaryContainer,
      error: error,
      onError: onError,
      errorContainer: errorContainer,
      onErrorContainer: onErrorContainer,
      surface: surface,
      onSurface: onSurface,
      surfaceContainerHighest: surfaceVariant,
      onSurfaceVariant: onSurfaceVariant,
      outline: outline,
      outlineVariant: outlineVariant,
      shadow: shadow,
      scrim: scrim,
      inverseSurface: inverseSurface,
      onInverseSurface: inverseOnSurface,
      inversePrimary: inversePrimary,
    );
  }
}

class ExtendedColor {
  const ExtendedColor({
    required this.seed,
    required this.value,
    required this.light,
    required this.lightHighContrast,
    required this.lightMediumContrast,
    required this.dark,
    required this.darkHighContrast,
    required this.darkMediumContrast,
  });

  final Color seed;
  final Color value;
  final ColorFamily light;
  final ColorFamily lightHighContrast;
  final ColorFamily lightMediumContrast;
  final ColorFamily dark;
  final ColorFamily darkHighContrast;
  final ColorFamily darkMediumContrast;
}

class ColorFamily {
  const ColorFamily({
    required this.color,
    required this.onColor,
    required this.colorContainer,
    required this.onColorContainer,
  });

  final Color color;
  final Color onColor;
  final Color colorContainer;
  final Color onColorContainer;
}

/// アプリ独自のカスタムカラー
/// Material Design にマッピングできない色を ThemeExtension で定義
class CustomColors extends ThemeExtension<CustomColors> {
  const CustomColors({
    required this.textTertiary,
    required this.textOnDark,
    required this.statusPositive,
    required this.statusWarning,
    required this.star,
    required this.tabInactive,
  });

  factory CustomColors.light() {
    return const CustomColors(
      textTertiary: Color(0xFF9C9B99),
      textOnDark: Color(0xFFFFFFFF),
      statusPositive: Color(0xFF4D9B6A),
      statusWarning: Color(0xFFD4A64A),
      star: Color(0xFFFFD700),
      tabInactive: Color(0xFFA8A7A5),
    );
  }

  /// text-tertiary (#9C9B99)
  final Color textTertiary;

  /// text-on-dark (#FFFFFF)
  final Color textOnDark;

  /// status-positive (#4D9B6A)
  final Color statusPositive;

  /// status-warning (#D4A64A)
  final Color statusWarning;

  /// star (#FFD700)
  final Color star;

  /// tab-inactive (#A8A7A5)
  final Color tabInactive;

  @override
  ThemeExtension<CustomColors> copyWith({
    Color? textTertiary,
    Color? textOnDark,
    Color? statusPositive,
    Color? statusWarning,
    Color? star,
    Color? tabInactive,
  }) {
    return CustomColors(
      textTertiary: textTertiary ?? this.textTertiary,
      textOnDark: textOnDark ?? this.textOnDark,
      statusPositive: statusPositive ?? this.statusPositive,
      statusWarning: statusWarning ?? this.statusWarning,
      star: star ?? this.star,
      tabInactive: tabInactive ?? this.tabInactive,
    );
  }

  @override
  ThemeExtension<CustomColors> lerp(
    covariant ThemeExtension<CustomColors>? other,
    double t,
  ) {
    if (other is! CustomColors) {
      return this;
    }

    return CustomColors(
      textTertiary: Color.lerp(textTertiary, other.textTertiary, t)!,
      textOnDark: Color.lerp(textOnDark, other.textOnDark, t)!,
      statusPositive: Color.lerp(statusPositive, other.statusPositive, t)!,
      statusWarning: Color.lerp(statusWarning, other.statusWarning, t)!,
      star: Color.lerp(star, other.star, t)!,
      tabInactive: Color.lerp(tabInactive, other.tabInactive, t)!,
    );
  }
}

/// BuildContext extension for easy access to CustomColors
extension CustomColorsExtension on BuildContext {
  CustomColors get customColors => Theme.of(this).extension<CustomColors>()!;
}
