name: foundation
description: 'Foundation for animeguri.'
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  # No dependencies

dev_dependencies:
  very_good_analysis: ^5.1.0
