name: foundation
description: 'Foundation for animeguri.'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  very_good_analysis: ^10.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
